### ISSUE TITLE
TypeError: object of type 'numpy.int64' has no len()

### ISSUE THREAD

**Issue by chandan-angadi** [xl-sr/CAL#23]
(CAL) vaishu@vaishu-MacBookAir:~/Desktop/CAL$ python PythonClient/driving_benchmark.py -c Town01 -v -n test --corl-2017
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html

Using TensorFlow backend.
INFO: listening to server localhost:2000
WARNING:tensorflow:From /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING: From /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2020-01-05 18:35:54.487175: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-05 18:35:54.523621: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1799985000 Hz
2020-01-05 18:35:54.524289: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x562c4653f460 executing computations on platform Host. Devices:
2020-01-05 18:35:54.524348: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Building model.
{'block_type': b'GRU', 'no_nodes': 185, 'p': '027', 'seq_len': 14, 'conv_dp': False, 'dilation': 2}
Traceback (most recent call last):
  File "PythonClient/driving_benchmark.py", line 72, in <module>
    agent = CAL(args.city_name)
  File "/home/vaishu/Desktop/CAL/PythonClient/agents/CAL_agent/CAL_agent.py", line 65, in __init__
    self._neural_net = CAL_network()
  File "/home/vaishu/Desktop/CAL/PythonClient/agents/CAL_agent/perception/cal_network.py", line 83, in __init__
    self.model = ModelSingle()        
  File "/home/vaishu/Desktop/CAL/PythonClient/agents/CAL_agent/perception/cal_network.py", line 21, in __init__
    tup = reload_model_from_episode('full_model_ep_3936')
  File "/home/vaishu/Desktop/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 58, in reload_model_from_episode
    model = get_final_model()
  File "/home/vaishu/Desktop/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 317, in get_final_model
    b0, p0 = get_task_block(RED_LIGHT)
  File "/home/vaishu/Desktop/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 199, in get_task_block
    model, name = reload_model_from_episode(model_name)
  File "/home/vaishu/Desktop/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 61, in reload_model_from_episode
    model = get_model_master(params)
  File "/home/vaishu/Desktop/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 162, in get_model_master
    x0 = block(x, p, no_nodes)
  File "/home/vaishu/Desktop/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 111, in GRU_block
    x = CuDNNGRU(n)(x)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/recurrent.py", line 541, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py", line 81, in call
    if len(initial_state) != len(self.states):
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/recurrent.py", line 438, in states
    num_states = len(self.cell.state_size)
TypeError: object of type 'numpy.int64' has no len()

**Comment by AbdeslemSmahi** [comment]
did you manage to solve the problem?

**Comment by AbdeslemSmahi** [comment]
I found a solution , just cast the input of the function `CudnnGRU` to int

**Comment by chandan-angadi** [comment]
Hi

Are you  @AbdeslemSmahi able to run this repo??

**Comment by chandan-angadi** [comment]
I am facing with this issue

(CAL) vaishu@vaishu-MacBookAir:~/opt/CAL$ python PythonClient/driving_benchmark.py -c Town01 -v -n test --corl-2017
2020-01-21 15:21:52.877925: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-01-21 15:21:52.877997: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-01-21 15:21:52.878009: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "PythonClient/driving_benchmark.py", line 6, in <module>
    from agents.CAL_agent.CAL_agent import CAL
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/CAL_agent.py", line 14, in <module>
    from agents.CAL_agent.perception import CAL_network
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/__init__.py", line 1, in <module>
    from .cal_network import CAL_network
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/cal_network.py", line 1, in <module>
    from agents.CAL_agent.perception.model_functions import *
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 95
    x = TimeDistributed(tail_model.layers[1], name=tail_model.layers[1].name)(inp)
    ^
SyntaxError: invalid syntax

**Comment by AbdeslemSmahi** [comment]
> I am facing with this issue
> 
> (CAL) vaishu@vaishu-MacBookAir:~/opt/CAL$ python PythonClient/driving_benchmark.py -c Town01 -v -n test --corl-2017
> 2020-01-21 15:21:52.877925: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
> 2020-01-21 15:21:52.877997: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
> 2020-01-21 15:21:52.878009: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Traceback (most recent call last):
> File "PythonClient/driving_benchmark.py", line 6, in
> from agents.CAL_agent.CAL_agent import CAL
> File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/CAL_agent.py", line 14, in
> from agents.CAL_agent.perception import CAL_network
> File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/**init**.py", line 1, in
> from .cal_network import CAL_network
> File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/cal_network.py", line 1, in
> from agents.CAL_agent.perception.model_functions import *
> File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 95
> x = TimeDistributed(tail_model.layers[1], name=tail_model.layers[1].name)(inp)
> ^
> SyntaxError: invalid syntax

yes i ran it .
this is a syntax problem , verify the parenthesis.

**Comment by chandan-angadi** [comment]
could you @AbdeslemSmahi  please send me the code of model_function file?

**Comment by AbdeslemSmahi** [comment]
Sure,
[model_function](https://drive.google.com/file/d/1YKtIn1fTva0uP1wCfpSfV6-m_lKIclan/view?usp=sharing)

**Comment by chandan-angadi** [comment]
Thanks a lot @AbdeslemSmahi , but now I am facing with this issue. I am sorry to bother you but can you please have a look




essage = 'No such file or directory', flags = 0, o_flags = 0)
(CAL) vaishu@vaishu-MacBookAir:~/opt/CAL$ python PythonClient/driving_benchmark.py -c Town01 -v -n test --corl-2017
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Using TensorFlow backend.
INFO: listening to server localhost:2000
WARNING:tensorflow:From /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING: From /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2020-01-21 15:41:11.984395: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-21 15:41:12.006658: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3493065000 Hz
2020-01-21 15:41:12.007516: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x564478df9e50 executing computations on platform Host. Devices:
2020-01-21 15:41:12.007533: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Building model.
Traceback (most recent call last):
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _run_fn
    self._extend_graph()
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1352, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by {{node cu_dnngru_1/CudnnRNN}}with these attrs: [dropout=0, seed=87654321, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="gru", is_training=true, seed2=0]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[{{node cu_dnngru_1/CudnnRNN}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PythonClient/driving_benchmark.py", line 72, in <module>
    agent = CAL(args.city_name)
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/CAL_agent.py", line 67, in __init__
    self._neural_net = CAL_network()
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/cal_network.py", line 83, in __init__
    self.model = ModelSingle()        
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/cal_network.py", line 21, in __init__
    tup = reload_model_from_episode('full_model_ep_3936')
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 65, in reload_model_from_episode
    model = get_final_model()
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 323, in get_final_model
    b0, p0 = get_task_block(RED_LIGHT)
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 205, in get_task_block
    model, name = reload_model_from_episode(model_name)
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 71, in reload_model_from_episode
    model.load_weights(w_name)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/engine/saving.py", line 1237, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2960, in batch_set_value
    tf_keras_backend.batch_set_value(tuples)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2880, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 482, in get_session
    _initialize_variables(session)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 758, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by node cu_dnngru_1/CudnnRNN (defined at /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:297) with these attrs: [dropout=0, seed=87654321, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="gru", is_training=true, seed2=0]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[node cu_dnngru_1/CudnnRNN (defined at /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:297) ]]

Caused by op 'cu_dnngru_1/CudnnRNN', defined at:
  File "PythonClient/driving_benchmark.py", line 72, in <module>
    agent = CAL(args.city_name)
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/CAL_agent.py", line 67, in __init__
    self._neural_net = CAL_network()
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/cal_network.py", line 83, in __init__
    self.model = ModelSingle()
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/cal_network.py", line 21, in __init__
    tup = reload_model_from_episode('full_model_ep_3936')
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 65, in reload_model_from_episode
    model = get_final_model()
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 323, in get_final_model
    b0, p0 = get_task_block(RED_LIGHT)
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 205, in get_task_block
    model, name = reload_model_from_episode(model_name)
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 68, in reload_model_from_episode
    model = get_model_master(params)
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 167, in get_model_master
    x0 = block(x, p, no_nodes)
  File "/home/vaishu/opt/CAL/PythonClient/agents/CAL_agent/perception/model_functions.py", line 119, in GRU_block
    x = CuDNNGRU(int(n))(x)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/recurrent.py", line 541, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py", line 90, in call
    output, states = self._process_batch(inputs, initial_state)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py", line 297, in _process_batch
    is_training=True)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 1713, in __call__
    seed=self._seed)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 1102, in _cudnn_rnn_no_input_c
    direction, dropout, seed, name)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 1014, in _cudnn_rnn
    outputs, output_h, output_c, _ = gen_cudnn_rnn_ops.cudnn_rnn(**args)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 142, in cudnn_rnn
    seed2=seed2, is_training=is_training, name=name)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNN' used by node cu_dnngru_1/CudnnRNN (defined at /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:297) with these attrs: [dropout=0, seed=87654321, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="gru", is_training=true, seed2=0]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[node cu_dnngru_1/CudnnRNN (defined at /home/vaishu/anaconda3/envs/CAL/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py:297) ]]

**Comment by chandan-angadi** [comment]
The above issue is because I have installed tensorflow==1.3.2 
if I install tf 2.0 I will get the below error 

ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by AbdeslemSmahi** [comment]
@chandanavgermany are you on GPU?

**Comment by chandan-angadi** [comment]
@AbdeslemSmahi Yeah I have Nvidia GTX force.

**Comment by AbdeslemSmahi** [comment]
make sure that you installed the GPU version of tensorflow.

**Comment by chandan-angadi** [comment]
@AbdeslemSmahi  I have installed the latest GPU version of tensorflow which is mentioned in their official website. which one you are using?

**Comment by chandan-angadi** [comment]
Which version of tensorflow??

**Comment by AbdeslemSmahi** [comment]
`tensorflow 1.14.0`

**Comment by chandan-angadi** [comment]
I have changed the tensorflow version but still facing the same issue. Any idea? What might be the problem @AbdeslemSmahi

**Comment by chandan-angadi** [comment]
Hey I fixed the above issue @AbdeslemSmahi,   now I am facing  
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'agents/CAL_agent/controller/params/general_params.txt'

File is there but its not accessing.
