### ISSUE TITLE
data directory error

### ISSUE THREAD

**Issue by robotsoft** [xl-sr/CAL#3]
Hello,

When I tried to run `python driving_benchmark.py -c Town02 -v -n test`, I encountered the following error. 

```
Traceback (most recent call last):
  File "driving_benchmark.py", line 72, in <module>
    agent = CAL(args.city_name)
  File "/home/xxx/CAL/PythonClient/agents/CAL_agent/CAL_agent.py", line 61, in __init__
    self._centerlines = Centerlines(city_name)
  File "/home/xxx/CAL/PythonClient/agents/CAL_agent/plans/centerlines.py", line 25, in __init__
    self.load_centerlines(dir_path, city)
  File "/home/xxx/CAL/PythonClient/agents/CAL_agent/plans/centerlines.py", line 61, in load_centerlines
    self.straight, self.straight_grad = load_array(file_lines)
  File "/home/xxx/CAL/PythonClient/agents/CAL_agent/plans/centerlines.py", line 15, in load_array
    return bcolz.open(fname)[:]
  File "/usr/local/lib/python2.7/dist-packages/bcolz/toplevel.py", line 140, in open
    return bcolz.carray(rootdir=rootdir, mode=mode)
  File "bcolz/carray_ext.pyx", line 1068, in bcolz.carray_ext.carray.__cinit__
  File "bcolz/carray_ext.pyx", line 1266, in bcolz.carray_ext.carray._open_carray
IOError: data directory does not exist
```

**Comment by geromidg** [comment]
Hi @xl-sr, from gitignore, it seems that "data" directories are ignored.
Could you please share the full centerlines data? Thanks.

**Comment by xl-sr** [comment]
@geromidg great catch, thanks! It's fixed now.
